version: "3.7"

services:
  broker:
    container_name: broker
    build:
      context: ./
    ports:
      - 27172:1883
      - 38283:8883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
