version: "3.7"
services:
  broker:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
